version: '3'
services:
  

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: emeelan
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - "5434:5432"

    volumes:
      - ./techserverdata:/var/lib/postgresql/data